version: "3.5"

services:
  hlds:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cstrike/addons:/home/steam/hlds/cstrike/addons
      - ./cstrike/logs:/home/steam/hlds/cstrike/logs
    ports:
      - "27015:27015"
      - "27015:27015/udp"
    environment:
      - RCON_PASSWORD=""
      - SV_PASSWORD=""
      - MAXPLAYERS="24"
      - MAPNAME="de_dust2"
