// C:\HL\cstrike\maps\cs_petare.res - created with RESGen v1.10
// RESGen is made by Jeroen "ShadowLord" Bogers
// URL: http://www.unitedadmins.com/mapRESGEN.asp
// E-MAIL: resgen@hltools.com
// Res creation date, GMT timezone (dd-mm-yyyy): 10-01-2003

// .res entries:
halflife.wad
cstrike.wad
cs_petare.wad
gfx/env/desup.tga
gfx/env/desdn.tga
gfx/env/deslf.tga
gfx/env/desrt.tga
gfx/env/desft.tga
gfx/env/desbk.tga
sound/nolepegue.wav
sound/ambience/lv6.wav
